### ISSUE TITLE
Writing posts doesn't capitalise/auto-correct

### ISSUE THREAD

**Issue by IBBoard** [vanita5/twittnuker#74]
The tweet writing box used to do the standard Android capitalisation (including "auto-correcting" the letter "i" to "I"). Recently something broke and it doesn't - everything is just lower-case.

Now I *could* just tweet in lower-case, but that'd be crass and uneducated. Or I could manually capitalise, but that's extra effort!

![screenshot_2015-11-23-20-11-48](https://cloud.githubusercontent.com/assets/388582/11348510/e74e00d2-921e-11e5-93a3-9878a890c5a9.png)

**Comment by vanita5** [comment]
autocorrection issues should've been resolved with version 0.7.8.

Have you tried the latest version?

**Comment by IBBoard** [comment]
Yup, works now. The update only seems to have come in today, though.

**Comment by vanita5** [comment]
Released it yesterday, but the Play Store publishes the update a few hours later, depending on the country you live in.

Thanks! :)

**Comment by IBBoard** [comment]
Oddly, it worked for a bit after the update and now it is back to broken. Tried a full close, swipe to quit and Force Close from settings in case some process was cached and still the same.

**Comment by vanita5** [comment]
That's really weird... is autocorrection broken again as well?
Are you sure, you are still using the latest version?

**Comment by IBBoard** [comment]
Yep - About page days 0.7.8. Got the update the other day when I closed this. It worked for a day or so and is now not autocorrecting/capitalising again.

Nexus 4 running Android 5.1.1

**Comment by IBBoard** [comment]
[Edit] Actually, it is a more subtle bug. Autocorrect works when I type character by character (e.g. i to I and autocorrrect to autocorrect) but auto-capitalisation isn't working (so tweets start lower-case, as do new sentences after a full stop)

**Comment by vanita5** [comment]
fixed for a while now

**Comment by IBBoard** [comment]
Cool. Hopefully the release will hit Google Play some time soon, then :) I can still only see 0.7.8 at the moment.
